export enum ListContextualBarEnum {
	VIEW_ID = 'list-reply-view-id',
	SEND = 'Send',
	EDIT = 'Edit',
	DELETE = 'Delete',
	REPLY_OVERFLOW_BLOCKID = 'list-reply-overflow-block-id',
	REPLY_OVERFLOW_ACTIONID = 'list-reply-overflow-action-id',
	LIST_REPLY_CLOSE_ACTION_ID = 'list-reply-close-action-id',
	LIST_REPLY_CLOSE_BLOCK_ID = 'list-reply-close-block-id',
	CLOESE_BUTTON_TEXT = 'Close',
	SEARCH_BLOCK_ID = 'list-reply-search-block-id',
	SEARCH_ACTION_ID = 'list-reply-search-action-id',
	REFRESH_BUTTON_ACTIONID = 'list-reply-refresh-action-id',
	REFRESH_BUTTON_BLOCKID = 'list-reply-refresh-block-id',
}
